import React from "react";
import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Board from "./Board";

import { useState, useEffect } from "react";

const Game = () => {

  // persist user from Login Page by grabbing from localStorage
  const [user, setUser] = useState(null);
  useEffect(() => {
    const loggedInUser = localStorage.getItem("user");
    if (loggedInUser) {
      const foundUser = JSON.parse(loggedInUser); // JSON.parse() turns JSON object into Javascript object
      setUser(foundUser);
    }
  }, []);

  return (
    <>
      <Head>
        <title>omok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* Conditionally render the user email */}
        {user && (user as any).email ? (
          <div>{(user as any).email} is logged in</div>
        ) : null}
        <h1>Omok - Connect 5</h1>
        <div>
          <Board />
        </div>
      </main>
    </>
  );
};

export default Game;
