import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";

import LoginForm from "./LoginForm";

// Called a  Functional component
const Login = () => {
  // one method to nav pages
  const router = useRouter();

  const navigateToGame = () => {
    router.push("/frontend/Game");
    return;
  };

  return (
    <div className={styles.login}>
      <Head>
        <title>omok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>This is the Login page.</p>
      </div>
      <div>
        <button onClick={navigateToGame}>Go to Game</button>
      </div>
      {/* <LoginForm /> */}
      <div></div>
    </div>
  );
};

export default Login;

/* example of Class Component

export default class Login extends Component {
  render() {
    return (
      <div>Login</div>
    )
  }
}

*/
